added hotjar heatmap snippet
ukparliament/shop.parliament.uk pull request #114
Opened 2018-02-26 09:21 UTC by gts-gi

2018-02-26 12:06 UTC, jakemulley requested changes

2018-02-26 12:06 UTC, jakemulley commented on src/scripts/monitoring/hotjar.js
> +        h._hjSettings={hjid:771371,hjsv:6};
You should add `hjid` as a setting in the theme - via `settings_schema.json`. It will allow us to have a different HJID on devci.

2018-02-26 15:00 UTC, gts-gi commented
Completed setting hjid via settings_schema. It is being stored in JS var in theme.liquid after being read by settings_schema, and fed to hotjar.js.liquid (the settings object cannot be parsed directly in the file)

2018-03-01 10:22 UTC, jakemulley approved these changes

2018-03-01 10:40 UTC, closed without merging